// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDevices() {
  return window['go']['main']['App']['GetDevices']();
}

export function GetEffects() {
  return window['go']['main']['App']['GetEffects']();
}

export function GetPitches() {
  return window['go']['main']['App']['GetPitches']();
}

export function GetSpeakers() {
  return window['go']['main']['App']['GetSpeakers']();
}

export function GetTTS(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTTS'](arg1, arg2, arg3, arg4);
}

export function IsPlaying() {
  return window['go']['main']['App']['IsPlaying']();
}

export function PlayAudio(arg1, arg2) {
  return window['go']['main']['App']['PlayAudio'](arg1, arg2);
}
